##### An initial draft for numpy array realities

In [2]:
import numpy as np
import pandas as pd

In [92]:
#Create a 3X5 numpy array

my_array=np.arange(15).reshape(3,5)

#arange() method provides the array's range
#reshape() method provides the arrays shape in terms of number of column and rows (columns, columns)

print(my_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [93]:
#A few characteristics of my array

#Use ndim to determione the number of dimensions of the array

print("Number of dimensions", end=': ')
print(my_array.ndim)
print()


#Use shape to determione the arrays shape (rows, columns)
print("Array shape", end=': ')
print(my_array.shape)
print()


#Use size to determione the arrays size- number of elements within the array
print("Array size", end=': ')
print(my_array.size)
print()

Number of dimensions: 2

Array shape: (3, 5)

Array size: 15



In [94]:
#The numpy arange() method
#Arguements include the starting value, the last value and the value for increments

#Create an array that start with the value 1, ends at 19 and whose values increase by 2

np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [103]:
#Create an 3 dimension array of zeros with the shape (2, 2) using the zeros() method

sufuri=np.zeros((2,2,3))
#print(sufuri.ndim)
print(sufuri)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [71]:
#Create an 3 dimension array of ones with the shape (2, 2) using the ones() method

np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [72]:
#Create an empty array of with the shape (9, 9)

np.empty((9,9))

#Creates a random array of values every other time the empty() method is rum

array([[1.02101932e-311, 1.02101932e-311, 1.02104311e-311,
        1.02104312e-311, 1.02103740e-311, 1.02104312e-311,
        1.02103950e-311, 1.02104312e-311, 1.02104312e-311],
       [1.02104312e-311, 1.02101931e-311, 1.02101932e-311,
        1.02104312e-311, 1.02102029e-311, 1.02104312e-311,
        1.02104015e-311, 1.02104021e-311, 1.02101933e-311],
       [1.02104023e-311, 1.02103715e-311, 1.02102011e-311,
        1.02101931e-311, 1.02103893e-311, 1.02103893e-311,
        1.02103891e-311, 1.02103891e-311, 1.02103716e-311],
       [1.02103898e-311, 1.02103890e-311, 1.02103889e-311,
        1.02103889e-311, 1.02103889e-311, 1.02103743e-311,
        1.02102024e-311, 1.02101937e-311, 1.02103740e-311],
       [1.02103743e-311, 1.02103741e-311, 1.02103743e-311,
        1.02103743e-311, 1.02103743e-311, 1.02103743e-311,
        1.02103715e-311, 1.02103740e-311, 1.02103743e-311],
       [1.02103742e-311, 1.02103744e-311, 1.02103743e-311,
        1.02103744e-311, 1.02103744e-311, 1.0210374

In [77]:
#Create an array from a list
#This is supposed to give us more control over its elements

my_list=np.array([4, 6, 12])
print(my_list)

[ 4  6 12]


In [80]:
#Create an array from a tuple
#This is supposed to give us more control over its elements

my_tuple=np.array((4, 6, 12))
print(my_tuple)

[ 4  6 12]


In [81]:
#Craete a multidimensional array from a list

poly_array=np.array([[3, 4], [1, 2], [7, 8], [5, 6]])
print(poly_array)

[[3 4]
 [1 2]
 [7 8]
 [5 6]]


In [104]:
#Create an array with 16 observations (0-15) and with the shape of 2 rows and 2 columns

other_array=np.arange(16).reshape(2,2,4)
print(other_array.ndim)
print(other_array)

3
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### Array Operations

In [112]:
#Arithmetic operations are generally apply/ are done to every individual observation in the array
#The operation prints out the results of the operation which is done elementwise/per observation

operations_array= np.array([2, 3, 4, 5, 6, 7, 8])

#Multiplication
operations_array*2

#Square
operations_array**2

#Cosine
np.cos(operations_array)

#Boolean
operations_array > 6

#Something to note is that array operations do not change the original observations
#However, the results of the operations can be stored in a new variable or the initial variable
#Storing the results in the original variable will overwrite the initial observations

array([False, False, False, False, False,  True,  True])

In [125]:
#Undertake slicing and indexing of our array
#Not much of a difference from other python data structures

#Create array

si_array=np.arange(10)**2
print(si_array)


#Select the observation/value of 4 in our array
si_array[2]

#Select the observations/values starting from 4 to 26 in our array
si_array[2:7]

#Select all the observations
si_array[:]                  #This is similar to print(varibale_name)

[ 0  1  4  9 16 25 36 49 64 81]


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [134]:
#Array observations iteration
#Create an array of 20 observations then square said obsaervation

itr_array=np.arange(8)**2
print(itr_array)

#Go ye and iterate

for observations in itr_array:
    print(observations)

[ 0  1  4  9 16 25 36 49]
0
1
4
9
16
25
36
49


In [143]:
#Create a multidimensional array
second_itr_array=np.arange(20).reshape(4,5)
print(second_itr_array)

#Get the observation with the value 9
#The value is on the second row(index 1) and fifth colum(index 4)
second_itr_array[1, 4]

#Slice the multidimensional array created
#Technically it follows the following; var_name[start.row1:end.row, start.colum:end.column]

second_itr_array[1:4, 2:4]

#Remember end.row and end.column are excluded from the slice
#[start at row 1:end at row3, start at row 2: end at row3]--- the numbers indicate index


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 7,  8],
       [12, 13],
       [17, 18]])

## Array statistics

In [145]:
#Create a multidimensional array
#9 elements/observations with 3 rows and 3 columns

stats_array=np.arange(9).reshape(3,3)
print(stats_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Sum

In [179]:
#Statistics
#Sum
#The numpy sum() method, in most circumstances, is called by the syntax np.sum()

np.sum(stats_array)

#Or var_name.sum()
stats_array.sum()

36

In [180]:
#Aggregating the observations in an array, especially multidimensional one can be tricky
#When aggregating the values consider the fact that these arrays have multiple row and columns
#A problem could require aggregations to be done against either a row/column and so on

#Sum against the column
np.sum(stats_array, axis=0)
#OR
stats_array.sum(axis=0)

#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 columns

#Sum against the row
np.sum(stats_array, axis=1)
#OR
stats_array.sum(axis=1)

#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 rows

array([ 3, 12, 21])

### Minimum

In [181]:
#Statistics
#Minimum
#The numpy min() method, in most circumstances, is called by the syntax np.min()

np.min(stats_array)

#Or var_name.min()

stats_array.min()

0

In [182]:
#Aggregating the observations in an array, especially multidimensional one can be tricky
#When aggregating the values consider the fact that these arrays have multiple row and columns
#A problem could require aggregations to be done against either a row/column and so on

#Minimum against the column
np.min(stats_array, axis=0)
#OR
stats_array.min(axis=0)

#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 columns

#Minimum against the row
np.min(stats_array, axis=1)
#OR
stats_array.min(axis=1)

#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 rows

array([0, 3, 6])

### Maximum

In [183]:
#Statistics
#Maximum
#The numpy max() method, in most circumstances, is called by the syntax np.max()

np.max(stats_array)

#Or var_name.max()

stats_array.max()

8

In [184]:
#Aggregating the observations in an array, especially multidimensional one can be tricky
#When aggregating the values consider the fact that these arrays have multiple row and columns
#A problem could require aggregations to be done against either a row/column and so on

#Maximum against the column
np.max(stats_array, axis=0)
#OR
stats_array.max(axis=0)

#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 columns

#Maximum against the row
np.max(stats_array, axis=1)
#OR
stats_array.max(axis=1)

#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 rows

array([2, 5, 8])

### Average

In [185]:
#Statistics
#Average
#The numpy avergae() method, in most circumstances, is called by the syntax np.average()

np.average(stats_array)

4.0

In [186]:
#Aggregating the observations in an array, especially multidimensional one can be tricky
#When aggregating the values consider the fact that these arrays have multiple row and columns
#A problem could require aggregations to be done against either a row/column and so on

#Average against the column
np.average(stats_array, axis=0)


#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 columns

#Average against the row
np.average(stats_array, axis=1)

#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 rows

array([1., 4., 7.])

In [187]:
#Statistics
#Standard Deviation
#The numpy std() method, in most circumstances, is called by the syntax np.std()

np.std(stats_array)

2.581988897471611

In [188]:
#Aggregating the observations in an array, especially multidimensional one can be tricky
#When aggregating the values consider the fact that these arrays have multiple row and columns
#A problem could require aggregations to be done against either a row/column and so on

#Standard Deviation against the column
np.std(stats_array, axis=0)


#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 columns

#Standard Deviation against the row
np.std(stats_array, axis=1)

#This should result in an array with 3 obsevations to match the arrays shape(3,3)- 3 rows

array([0.81649658, 0.81649658, 0.81649658])

## Array Transformation

In [215]:
#Create an arange of 10 observations with the shape of 2 rows and 5 columns

trans_array=np.arange(20).reshape(4,5)
trans_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [216]:
#Confirm the arrays using shape

trans_array.shape

(4, 5)

### Transpose

In [227]:
#Transpose the array using T
#Transpose is the transformation of the shape of the data- rows to columns and vice versa

trans_array.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### Ravel

In [218]:
#Crash the dimensional aspects of the array using the ravel() method
#The method changes the arrays shape into a one dimension
#This might come in handy when iterating over the array
#It might also help when doing data validation on the arrays observations/values

trans_array.ravel()

#The ravel() method does not necessarily alter the original shape of our variable 
#Unless the results of the variable are stored in the initial variable (or another)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Reshape

In [226]:
#Reshape the array using the reshape() method
#Change it to the shape of a 3 dimension array with two column, two rows 

trans_array.reshape(2,2,5)

#The reshape() method does not necessarily alter the original shape of our variable as well
#Unless the results of the variable are stored in the initial variable (or another)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### Stacking

In [232]:
#Create a multidimensional array

stack_1= np.array([[8, -1], [4,9]])
stack_1

array([[ 8, -1],
       [ 4,  9]])

In [233]:
#Create a second multidimensional array

stack_2= np.array([[0.2, 0.9], [-0.02, 0.04]])
stack_2

array([[ 0.2 ,  0.9 ],
       [-0.02,  0.04]])

In [234]:
#Stack the two arrays together vertically

np.vstack((stack_1, stack_2))

#N/B: The order of the arrays specification matters
#Numpy stacks them orderly- first in and first out and so on

array([[ 8.  , -1.  ],
       [ 4.  ,  9.  ],
       [ 0.2 ,  0.9 ],
       [-0.02,  0.04]])

In [235]:
#Stack the two arrays together horizontally

np.hstack((stack_1, stack_2))

#N/B: The order of the arrays specification matters
#Numpy stacks them orderly- first in and first out and so on

array([[ 8.  , -1.  ,  0.2 ,  0.9 ],
       [ 4.  ,  9.  , -0.02,  0.04]])

### Splitting

In [240]:
#Horizontally stack two arrays and save their observations into a new variable

stack_uno= np.array([[8, -1], [4,9]])
stack_deux= np.array([[0.2, 0.9], [-0.02, 0.04]])


hrzntl_stack=np.hstack((stack_uno, stack_deux))

#Horizontal split the array into two using the hsplit() method
#The method takes two arguements- the variable/object of choice and the number of splits/arrays

np.hsplit(hrzntl_stack, 2)

[array([[ 8., -1.],
        [ 4.,  9.]]), array([[ 0.2 ,  0.9 ],
        [-0.02,  0.04]])]

In [242]:
#Vertically stack the two arrays and save their observations into a new variable

vrtcl_stack=np.vstack((stack_uno, stack_deux))

#Vertically split the array into two using the vsplit() method
#The method takes two arguements- the variable/object of choice and the number of splits/arrays

np.vsplit(vrtcl_stack, 2)

[array([[ 8., -1.],
        [ 4.,  9.]]), array([[ 0.2 ,  0.9 ],
        [-0.02,  0.04]])]